"""empty message

Revision ID: 059f4c95d1b5
Revises: 7d941f8272b0
Create Date: 2021-03-26 23:09:23.261016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059f4c95d1b5'
down_revision = '7d941f8272b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Userinfo', sa.Column('add', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Userinfo', 'add')
    # ### end Alembic commands ###
