"""empty message

Revision ID: 10f517c410f6
Revises: beefe4ac1c1e
Create Date: 2021-04-12 09:51:44.657724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f517c410f6'
down_revision = 'beefe4ac1c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['uploadata.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['Userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likedata')
    # ### end Alembic commands ###
