"""empty message

Revision ID: beefe4ac1c1e
Revises: 
Create Date: 2021-04-09 20:49:21.896781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beefe4ac1c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('uploadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('about', sa.String(length=500), nullable=False),
    sa.Column('pic', sa.String(length=200), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=400), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['uploadata.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['Userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentdata')
    op.drop_table('uploadata')
    op.drop_table('Userinfo')
    # ### end Alembic commands ###
